kmc_parallel: kmc_parallel.c mt19937-64.c mt64.h
	mpic++ -std=c++11 -o kmc_parallel kmc_parallel.c mt19937-64.c

kmc_serial: kmc_serial.c mt19937-64.c mt64.h
	g++ -std=c++11 -o kmc_serial kmc_serial.c mt19937-64.c
